---
driver:
  name: terraform
  variable_files:
    - testing.tfvars

provisioner:
  name: terraform

platforms:
  - name: ubuntu

transport:
  name: ssh
  path: ~/.ssh/your_ssh_key.pem

verifier:
  name: terraform
  groups:
    - name: default
      hostnames: public_dns
      username: ubuntu

suites:
  - name: default
