# frozen_string_literal: true
source "https://rubygems.org"

gem "bundler"
gem "test-kitchen"
gem "kitchen-terraform", "~> 2.0"
gem "awspec", "~> 0.6"
gem 'net-ssh','~> 2.9'
gem 'kitchen-verifier-awspec'
